# Generated by Django 4.2.2 on 2023-07-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='send_time',
            field=models.TimeField(verbose_name='Время рассылки'),
        ),
    ]
