# Generated by Django 4.2.2 on 2023-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_options_alter_customer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='Default subject', max_length=50, verbose_name='Тема рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Тема письма'),
        ),
    ]
