# Generated by Django 4.2.2 on 2023-07-05 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время рассылки'),
        ),
    ]
