# Generated by Django 4.2.2 on 2023-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsletter_subject_alter_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='Тема рассылки', max_length=50, verbose_name='Тема рассылки'),
        ),
    ]
