# Generated by Django 4.2.3 on 2023-07-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='send_time',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='body',
            field=models.TextField(default='', verbose_name='Содержание письма'),
            preserve_default=False,
        ),
    ]
