# Generated by Django 4.2.3 on 2023-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_message_body_remove_message_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Тема рассылки'),
        ),
    ]
