# Generated by Django 4.2.3 on 2023-07-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
